apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-localdisk
  namespace: jenkins-dev
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
