apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: serviceaccount-rolebinding-pod-reader
        namespace: default
subjects:
- kind: ServiceAccount
  name: serviceaccount-my-serviceaccount
  namespace: default
roleRef:
        kind: Role
        name: role-pod-reader
        apiGroup: rbac.authorization.k8s.io
          

