apiVersion: v1
kind: Pod
metadata:
  name: k8s-demo-pod
  namespace: default
spec:
  serviceAccountName: jenkins
  containers:
  - name: shell
    image: alpine:3.7
    command:
      - "sh"
      - "-c"
      - "sleep 3600"
