apiVersion: v1
kind: Service
metadata:
  name: service-clusterip
spec:
  type: ClusterIP
  selector:
    app: service-example
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
