apiVersion: v1
kind: Pod
metadata:
        name: pod-network-nginx
        namespace: networkpolicy-test
        labels:
                app: nginx
spec:
        containers:
        - name: nginx
          image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
        name: pod-network-busybox
        namespace: networkpolicy-test
        labels:
                app: client
spec:
        containers:
        - name: busybox
          image: radial/busyboxplus:curl
          command: ['sh', '-c', 'while true; do sleep 3600; done']




