apiVersion: v1
kind: Pod
metadata:
        name: pod-nodeselector
spec:
        nodeSelector:
                special: "true"
                worker: "true"
        containers:
        - name: nginx
          image: nginx:1.19.1

