apiVersion: v1
kind: Pod
metadata:
        name: pod-multicontainer
spec:
        containers:
        - name: nginx
          image: nginx
        - name: redis
          image: redis
        - name: couchbase
          image: couchbase
