apiVersion: v1
kind: Pod
metadata:
        name: pod-liveness
spec:
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'while true; do sleep 3600; done']
          livenessProbe:
                  exec:
                          command: ["echo", "Hello Partner!"]
                  initialDelaySeconds: 5
                  periodSeconds: 5
