apiVersion: v1
kind: Pod
metadata:
        name: pod-env
spec:
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'echo "configmap: $CONFIGMAPVAR secret: $SECRETVAR"']
          env:
          - name: CONFIGMAPVAR
            valueFrom:
                    configMapKeyRef:
                            name: config-my-configmap
                            key: key1
          - name: SECRETVAR
            valueFrom:
                    secretKeyRef:
                            name: config-my-secret
                            key: secretkey1
