apiVersion: v1
kind: Pod
metadata: 
  name: pod-service-test2
  namespace: service-test
spec:
  containers:
  - name: busybox
    image: radial/busyboxplus:curl
    command: ['sh', '-c', 'while true; do sleep 3600; done']

