apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: jenkins
  labels:
    k8s-app: s3-provider
  name: s3-provider
spec:
  selector:
    matchLabels:
      name: s3-provider
  template:
    metadata:
      labels:
        name: s3-provider
    spec:
      containers:
      - name: s3-provider
        image: senthilmnathan/my-s3fs:latest
        securityContext:
          privileged: true
        envFrom:
        - configMapRef:
            name: s3-config
        volumeMounts:
        - name: devfuse
          mountPath: /dev/fuse
        - name: mntdatas3fs
          mountPath: /var/s3fs
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: mntdatas3fs
        hostPath:
          path: /mnt/s3data
