apiVersion: v1
kind: Service
metadata:
  name: service-nodeport
spec:
  type: NodePort
  selector:
    app: service-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
