apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: s3-config
data:
  S3_REGION: "us-east-1"
  S3_BUCKET: "kubernetes-0002"
  AWS_KEY: "AKIA3ZMQ2BTI6BKQTYCM"
  AWS_SECRET_KEY: "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"
