apiVersion: apps/v1
kind: Deployment
metadata:
        name: deployment-my
spec:
        replicas: 3
        selector:
                matchLabels:
                        app: deployment-my
        template:
                metadata:
                        labels:
                                app: deployment-my
                spec:
                        containers:
                        - name: nginx
                          image: nginx:1.19.2
                          ports:
                          - containerPort: 80

