apiVersion: apps/v1
kind: Deployment
metadata:
          name: deploy-nginx
          labels:
                  app: deploy-nginx
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: deploy-nginx
        template:
                metadata:
                        labels:
                                app: deploy-nginx
                spec:
                        containers:
                        - name: nginx
                          image: nginx:1.14.2
                          ports:
                          - containerPort: 80
