apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-my
spec:
  storageClassName: sc-localdisk
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/output
