apiVersion: v1
kind: Pod
metadata:
        name: pod-sidecar
spec:
        containers:
        - name: publister
          image: busybox
          command: ['sh', '-c', 'while true; do echo logs data > /output/output.log; sleep 5; done']
          volumeMounts:
          - name: sharedvolume
            mountPath: /output
        - name: reader
          image: busybox
          command: ['sh', '-c', 'tail -f /input/output.log']
          volumeMounts:
          - name: sharedvolume
            mountPath: /input
        volumes:
        - name: sharedvolume
          emptyDir: {}

