apiVersion: v1
kind: Pod
metadata:
        name: pod-always
spec:
        restartPolicy: Always
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'sleep 10']
