apiVersion: v1
kind: Pod
metadata:
        name: pod-never
spec:
        restartPolicy: Never
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'sleep 10; bans']
