apiVersion: v1
kind: Pod
metadata:
        name: pod-onfailure
spec:
        restartPolicy: OnFailure
        containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'sleep 10; bandana sinha']
