apiVersion: v1
kind: Pod
metadata:
        name: pod-dnstest-busybox
spec:
        containers:
        - name: busybox
          image: radial/busyboxplus:curl
          command: ['sh', '-c', 'while true; do sleep 3600; done']
---
apiVersion: v1
kind: Pod
metadata:
        name: pod-dnstest-nginx
spec:
        containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80

